---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base




#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  [push, pull_request]

###############
# Set the Job #
###############



jobs:
  lint:
    name: Black auto formatting
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options:

      - name: Set up git 
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Checkout to the branch
        if: github.head_ref != ''
        run: |
          git symbolic-ref HEAD refs/heads/${{ github.head_ref }}
          git reset

      - name: Commit files
        run: |
          git add -u
          git diff --cached --quiet || git commit -m "Apply Black formatting"
          git push

  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: write
      packages: write
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          # Change to 'master' if your main branch differs
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
